# PRACTICAL 1

In [1]:
# QUE -1 (A)

import numpy as np
# Create a 2D array with random values
arr = np.random.rand(2,3)*10
arr1=arr.astype(int)
print(arr1)

[[9 0 8]
 [0 2 2]]


In [2]:
#calculate mean
mean = np.mean(arr1,axis=1)
print(mean)

[5.66666667 1.33333333]


In [3]:
#calculate standard deviation
std = np.std(arr1,axis=1)
print(std)

[4.02768199 0.94280904]


In [4]:
#calculate variance
var = np.var(arr1,axis=1)
print(var)

[16.22222222  0.88888889]


In [5]:
# B

#take user input
m=int(input("enter m:"))
n=int(input("enter n:"))

# creating a 2D array with integer elements
arr = np.arange(m*n).reshape(m,n)
print(arr)

enter m: 2
enter n: 3


[[0 1 2]
 [3 4 5]]


In [6]:
#print shape
print("Shape:",arr.shape)

Shape: (2, 3)


In [7]:
#print type
print("Data Types:",arr.dtype)

Data Types: int64


In [8]:
type(arr)

numpy.ndarray

In [9]:
#reshape array
arr.reshape(n,m)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
# C

#Create array with zero and non zero values
arr1 = np.array([1,0,5,np.nan,0,8])
print(arr1)

[ 1.  0.  5. nan  0.  8.]


In [11]:
#find index of zero elements
print("Zero Indices:",np.where(arr1==0))

Zero Indices: (array([1, 4]),)


In [12]:
#find index of non zero elements
print("Non-zero indices:",np.where(arr!=0))

Non-zero indices: (array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))


In [13]:
#find indices of NAN elements
print("NAN indices:",np.where(np.isnan(arr1)))

NAN indices: (array([3]),)


In [14]:
a=np.random.randn(2,2)
print(a)

[[-0.24785118  0.72680287]
 [ 0.48958913 -2.58301182]]


In [15]:
a.sum(axis=0)

array([ 0.24173795, -1.85620895])

In [16]:
a.sum(axis=1)

array([ 0.47895169, -2.09342269])

In [17]:
# D
arr1 = np.array([1,0,5,2,0,8])
arr2 = np.array([1,9,2,5,10,6])
ANS = np.cov(arr1,arr2)
print(ANS)

[[10.26666667 -3.8       ]
 [-3.8        13.1       ]]


In [18]:
arr1 = np.array([1,0,5,2,0,8])
arr2 = np.array([1,9,2,5,10,6])
ANS = np.corrcoef(arr1,arr2)
print(ANS)

[[ 1.         -0.32766739]
 [-0.32766739  1.        ]]


In [19]:
# E

sum_ans = arr1[0:5] + arr2[0:5]
print(sum_ans)

[ 2  9  7  7 10]


In [20]:
p = arr1[5: ] * arr2[5: ]
print(p)

[48]


In [21]:
# F

memory_size = arr1.nbytes
print(memory_size)

48


In [22]:
# G
m=int(input("enter m:"))
n=int(input("enter n:"))

# creating a 2D array with integer elements
arr = np.arange(m*n).reshape(m,n)
print(arr)

enter m: 3
enter n: 4


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
arr_swap= arr.copy()
arr_swap[[0,1]]=arr_swap[[1,0]]
print(arr_swap)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]


In [24]:
arr_rev=arr_swap.copy()
arr_rev[:,1]=arr_rev[::-1,1]
print(arr_rev)

[[ 4  9  6  7]
 [ 0  1  2  3]
 [ 8  5 10 11]]
